# Generated by Django 5.2.3 on 2025-07-15 17:06

import fernet_fields.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerinstance',
            name='environment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='towerinstance',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='towerinstance',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='towerinstance',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
