# Generated by Django 5.2.3 on 2025-07-17 10:03

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0002_towerinstance_environment_towerinstance_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tower_instance', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='credentials',
                    to='tower.towerinstance'
                )),
            ],
        ),
    ]
