# Generated by Django 5.2.3 on 2025-07-18 04:22

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0003_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
