# Generated by Django 5.2.3 on 2025-07-18 09:02

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0004_alter_credential_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('tower_instance', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='environments',
                    to='tower.towerinstance'
                )),
            ],
        ),
    ]
