# Generated by Django 5.3.3 on 2025-08-01 00:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0000_auditing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default="https://ansible-tower.dev.echonet/")),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
